server:
  port: 8080
  tomcat.uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3308/test
    username: root
    password:123456

mybatis:
  type-aliases-package: com.model